version: "1"
services:
  app:
    image: anthony-front-end
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    networks:
      - anthony-photo-net
    volumes:
      - anthony-photo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: anthony_photo_db
  server:
    image: anthony-back-end
    build:
      context: ./anthony-photography-be
      dockerfile: Dockerfile
    networks:
      - anthony-photo-net
    ports:
      - "8082:8082"
    environment:
      DB_PASSWORD: secret
    depends_on:
      - mysql
volumes:
  anthony-photo-mysql-data:
networks:
  anthony-photo-net: